-- ============================================================
-- SEED DATA
-- Run AFTER creating the admin user through Supabase Auth
-- ============================================================

-- NOTE: First create admin user via Supabase Auth dashboard or API:
-- Email: admin@backbench.local
-- Password: CHANGE_THIS_PASSWORD
-- Then get the UUID and replace 'ADMIN_USER_UUID' below

-- Create admin profile (replace ADMIN_USER_UUID with actual UUID from auth.users)
-- INSERT INTO profiles (id, username, display_name, role, can_invite, invite_slots, onboarding_done)
-- VALUES (
--   'ADMIN_USER_UUID',
--   'adminthereal',
--   'Admin',
--   'admin',
--   TRUE,
--   999,
--   TRUE
-- );

-- Seed initial invite codes (generated by admin)
-- Replace ADMIN_USER_UUID with actual admin UUID after creating admin profile
-- INSERT INTO invites (code, created_by, status) VALUES
--   ('VHSS-ALPHA-001', 'ADMIN_USER_UUID', 'active'),
--   ('VHSS-ALPHA-002', 'ADMIN_USER_UUID', 'active'),
--   ('VHSS-ALPHA-003', 'ADMIN_USER_UUID', 'active'),
--   ('VHSS-ALPHA-004', 'ADMIN_USER_UUID', 'active'),
--   ('VHSS-ALPHA-005', 'ADMIN_USER_UUID', 'active'),
--   ('VHSS-BETA-001', 'ADMIN_USER_UUID', 'active'),
--   ('VHSS-BETA-002', 'ADMIN_USER_UUID', 'active'),
--   ('VHSS-BETA-003', 'ADMIN_USER_UUID', 'active'),
--   ('VHSS-BETA-004', 'ADMIN_USER_UUID', 'active'),
--   ('VHSS-BETA-005', 'ADMIN_USER_UUID', 'active');

-- Class list reference (used in UI dropdowns)
-- Science stream
-- 12 Science A, 12 Science B
-- 11 Science A, 11 Science B
-- Commerce stream
-- 12 Commerce A, 12 Commerce B
-- 11 Commerce A, 11 Commerce B

-- Default app settings (already inserted by schema.sql)
-- Just verify it exists:
-- SELECT * FROM app_settings;
